# Generated by Django 5.0.6 on 2024-07-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_message_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='update',
            new_name='updated',
        ),
    ]
